export {
  ReactOriginal,
  COriginal,
  NodejsOriginal,
  CplusplusOriginal,
  ExpressOriginal,
  MongodbOriginal,
  JavascriptOriginal,
  TypescriptOriginal,
  PythonOriginal,
  Html5Original,
  Css3Original,
  SassOriginal,
  AmazonwebservicesOriginalWordmark,
  DockerPlain,
  GitOriginal,
  TailwindcssPlain,
  BootstrapPlain,
  MysqlOriginalWordmark,
  FlaskOriginal,
  JavaOriginal,
  JupyterOriginalWordmark,
  SocketioOriginal,
  NextjsOriginal,
  PostgresqlOriginal,
  JenkinsOriginal,
  FigmaOriginal,
} from 'devicons-react'